'''


The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''


def getTriangleNum(n):
	return int((n*(n+1))/2)




def findDivisors(m):
	divisor_list = []
	for i in range(1,m):
		if(m%i==0):
			divisor_list.append(i)
	divisor_list.append(m)
	return divisor_list

def findNumberOfDivisors(n):
	sqroot,t = int(n**0.5),0
	for factor in range(1,sqroot+1):
		if n % factor == 0:
			t += 2 # both factor and N/factor
	if sqroot*sqroot == n: t = t - 1 # if sqroot is a factor then we counted it twice, so subtract 1
	return t



n=1
while(True):
	if(findNumberOfDivisors(getTriangleNum(n))>500):
		ans = getTriangleNum(n)
		break
	n+=1


print("Divisors: ",findDivisors(getTriangleNum(n)), "\n Answer: ", ans, "is the ", n ,"th triangular number")

		