[package]
name = "n095_amicable_chains"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
rstest = "0.17.0"

[profile.release]
opt-level = 3