[package]
name = "power_power_tripes"
version = "0.1.0"
authors = ["jvals <jvals@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
